
package com.xdev.rcdemo.globalactions.ui;

import com.vaadin.annotations.Push;
import com.vaadin.annotations.Theme;
import com.vaadin.server.VaadinRequest;
import com.vaadin.shared.communication.PushMode;
import com.vaadin.shared.ui.MarginInfo;
import com.vaadin.shared.ui.ui.Transport;
import com.vaadin.ui.Alignment;
import com.vaadin.ui.Button;
import com.vaadin.ui.CustomComponent;
import com.xdev.rcdemo.globalactions.ui.actions.SaveAction;
import com.xdev.ui.XdevButton;
import com.xdev.ui.XdevGridLayout;
import com.xdev.ui.XdevHorizontalLayout;
import com.xdev.ui.XdevPanel;
import com.xdev.ui.XdevUI;
import com.xdev.ui.navigation.Navigation;
import com.xdev.ui.navigation.XdevNavigator;

@Push(value = PushMode.MANUAL, transport = Transport.LONG_POLLING)
@Theme("rapidclipse_demo_globalactions")
public class MainUI extends XdevUI {
	public MainUI() {
		super();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public void init(final VaadinRequest request) {
		this.initUI();
	}

	/**
	 * Event handler delegate method for the {@link XdevButton} {@link #cmdView1}.
	 *
	 * @see Button.ClickListener#buttonClick(Button.ClickEvent)
	 * @eventHandlerDelegate Do NOT delete, used by UI designer!
	 */
	private void cmdView1_buttonClick(final Button.ClickEvent event) {
		Navigation.to("").navigate();
	}

	/**
	 * Event handler delegate method for the {@link XdevButton} {@link #cmdView2}.
	 *
	 * @see Button.ClickListener#buttonClick(Button.ClickEvent)
	 * @eventHandlerDelegate Do NOT delete, used by UI designer!
	 */
	private void cmdView2_buttonClick(final Button.ClickEvent event) {
		Navigation.to("view2").navigate();
	}

	/**
	 * Event handler delegate method for the {@link XdevButton} {@link #cmdView3}.
	 *
	 * @see Button.ClickListener#buttonClick(Button.ClickEvent)
	 * @eventHandlerDelegate Do NOT delete, used by UI designer!
	 */
	private void cmdView3_buttonClick(final Button.ClickEvent event) {
		Navigation.to("view3").navigate();
	}

	/*
	 * WARNING: Do NOT edit!<br>The content of this method is always regenerated by
	 * the UI designer.
	 */
	// <generated-code name="initUI">
	private void initUI() {
		this.gridLayout = new XdevGridLayout();
		this.horizontalLayout = new XdevHorizontalLayout();
		this.cmdView1 = new XdevButton();
		this.cmdView2 = new XdevButton();
		this.cmdView3 = new XdevButton();
		this.button = new XdevButton();
		this.panel = new XdevPanel();
		this.navigator = new XdevNavigator(this, this.panel);

		this.horizontalLayout.setMargin(new MarginInfo(false));
		this.cmdView1.setCaption("View1");
		this.cmdView1.setStyleName("borderless");
		this.cmdView2.setCaption("View2");
		this.cmdView2.setStyleName("borderless");
		this.cmdView3.setCaption("View3");
		this.cmdView3.setStyleName("borderless");
		this.button.setStyleName("friendly");
		final SaveAction saveAction = new SaveAction();
		this.button.setAction(saveAction);
		this.navigator.addView("", View1.class);
		this.navigator.addView("view2", View2.class);
		this.navigator.addView("view3", View3.class);

		this.cmdView1.setSizeUndefined();
		this.horizontalLayout.addComponent(this.cmdView1);
		this.horizontalLayout.setComponentAlignment(this.cmdView1, Alignment.MIDDLE_CENTER);
		this.cmdView2.setSizeUndefined();
		this.horizontalLayout.addComponent(this.cmdView2);
		this.horizontalLayout.setComponentAlignment(this.cmdView2, Alignment.MIDDLE_CENTER);
		this.cmdView3.setSizeUndefined();
		this.horizontalLayout.addComponent(this.cmdView3);
		this.horizontalLayout.setComponentAlignment(this.cmdView3, Alignment.MIDDLE_CENTER);
		this.button.setSizeUndefined();
		this.horizontalLayout.addComponent(this.button);
		this.horizontalLayout.setComponentAlignment(this.button, Alignment.MIDDLE_CENTER);
		final CustomComponent horizontalLayout_spacer = new CustomComponent();
		horizontalLayout_spacer.setSizeFull();
		this.horizontalLayout.addComponent(horizontalLayout_spacer);
		this.horizontalLayout.setExpandRatio(horizontalLayout_spacer, 1.0F);
		this.gridLayout.setColumns(1);
		this.gridLayout.setRows(2);
		this.horizontalLayout.setWidth(100, Unit.PERCENTAGE);
		this.horizontalLayout.setHeight(-1, Unit.PIXELS);
		this.gridLayout.addComponent(this.horizontalLayout, 0, 0);
		this.panel.setSizeFull();
		this.gridLayout.addComponent(this.panel, 0, 1);
		this.gridLayout.setColumnExpandRatio(0, 10.0F);
		this.gridLayout.setRowExpandRatio(1, 10.0F);
		this.gridLayout.setSizeFull();
		this.setContent(this.gridLayout);
		this.setSizeFull();

		this.cmdView1.addClickListener(event -> this.cmdView1_buttonClick(event));
		this.cmdView2.addClickListener(event -> this.cmdView2_buttonClick(event));
		this.cmdView3.addClickListener(event -> this.cmdView3_buttonClick(event));
	} // </generated-code>

	// <generated-code name="variables">
	private XdevButton cmdView1, cmdView2, cmdView3, button;
	private XdevNavigator navigator;
	private XdevHorizontalLayout horizontalLayout;
	private XdevPanel panel;
	private XdevGridLayout gridLayout;
	// </generated-code>
}