
package com.xdev.rcdemo.globalactions.ui;

import com.vaadin.data.Property;
import com.vaadin.navigator.ViewChangeListener;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.Notification;
import com.xdev.rcdemo.globalactions.ui.actions.SaveHandler;
import com.xdev.ui.XdevCheckBox;
import com.xdev.ui.XdevGridLayout;
import com.xdev.ui.XdevView;
import com.xdev.ui.action.XdevActionManager;

public class View1 extends XdevView implements SaveHandler {

	/**
	 *
	 */
	public View1() {
		super();
		this.initUI();
	}

	@Override
	public void enter(final ViewChangeListener.ViewChangeEvent event) {
		super.enter(event);

	}

	@Override
	public void save() {
		Notification.show("View1 saved!");
	}

	@Override
	public boolean isSaveEnabled() {
		return this.chkSaveEnabled.getValue();
	}

	private void fireSaveHandlerChanged() {
		XdevActionManager.getCurrent().fireContextSensitiveHandlerChanged(SaveHandler.class, this);
	}

	/**
	 * Event handler delegate method for the {@link XdevCheckBox}
	 * {@link #chkSaveEnabled}.
	 *
	 * @see Property.ValueChangeListener#valueChange(Property.ValueChangeEvent)
	 * @eventHandlerDelegate Do NOT delete, used by UI designer!
	 */
	private void chkSaveEnabled_valueChange(final Property.ValueChangeEvent event) {
		fireSaveHandlerChanged();
	}

	/*
	 * WARNING: Do NOT edit!<br>The content of this method is always regenerated by
	 * the UI designer.
	 */
	// <generated-code name="initUI">
	private void initUI() {
		this.gridLayout = new XdevGridLayout();
		this.chkSaveEnabled = new XdevCheckBox();

		this.chkSaveEnabled.setCaption("Save Enabled");
		this.chkSaveEnabled.setImmediate(true);

		this.gridLayout.setColumns(2);
		this.gridLayout.setRows(2);
		this.chkSaveEnabled.setSizeUndefined();
		this.gridLayout.addComponent(this.chkSaveEnabled, 0, 0);
		final CustomComponent gridLayout_hSpacer = new CustomComponent();
		gridLayout_hSpacer.setSizeFull();
		this.gridLayout.addComponent(gridLayout_hSpacer, 1, 0, 1, 0);
		this.gridLayout.setColumnExpandRatio(1, 1.0F);
		final CustomComponent gridLayout_vSpacer = new CustomComponent();
		gridLayout_vSpacer.setSizeFull();
		this.gridLayout.addComponent(gridLayout_vSpacer, 0, 1, 0, 1);
		this.gridLayout.setRowExpandRatio(1, 1.0F);
		this.gridLayout.setSizeFull();
		this.setContent(this.gridLayout);
		this.setSizeFull();

		this.chkSaveEnabled.addValueChangeListener(new Property.ValueChangeListener() {
			@Override
			public void valueChange(final Property.ValueChangeEvent event) {
				View1.this.chkSaveEnabled_valueChange(event);
			}
		});
	} // </generated-code>

	// <generated-code name="variables">
	private XdevCheckBox chkSaveEnabled;
	private XdevGridLayout gridLayout;
	// </generated-code>

}
